-- Flyway Migration Script: Create Schemas for BookLink

-- Create Users Table
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)        NOT NULL,
    email    VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    location VARCHAR(255)
);

-- Create Books Table
CREATE TABLE books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    author       VARCHAR(255) NOT NULL,
    isbn         VARCHAR(13),
    genre        VARCHAR(100),
    condition    VARCHAR(50)  NOT NULL,
    availability VARCHAR(50)  NOT NULL,
    owner_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

-- Create Transactions Table
CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id          BIGINT      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    requester_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    owner_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type             VARCHAR(50) NOT NULL,
    status           VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    amount           DECIMAL(10, 2)
);

-- Create Wishlists Table
CREATE TABLE wishlists
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id    BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Reviews Table
CREATE TABLE reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    rating         INT CHECK (rating >= 1 AND rating <= 5),
    comment        TEXT,
    reviewer_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

-- Create Categories Table
CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

-- Add Genre to Books Table as a Foreign Key
ALTER TABLE books
    ADD CONSTRAINT fk_genre_category FOREIGN KEY (genre) REFERENCES categories (name) ON DELETE SET NULL;
